#cloud-config
package_update: true
packages:
  - ca-certificates
  - curl

write_files:
  - path: /opt/app/docker-compose.yml
    permissions: '0644'
    content: |
      services:
        planets-mvc:
          image: jtaiwo1/planets-mvc-cloud:latest
          ports:
            - "80:80"
          restart: always
          depends_on:
            - planets-db
          networks:
            - planets-network

        planets-db:
          image: jtaiwo1/planets-db-cloud:latest
          restart: always
          networks:
            - planets-network

      networks:
        planets-network:

runcmd:
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl enable --now docker
  - usermod -aG docker azureuser
  - docker compose -f /opt/app/docker-compose.yml up -d